const buildingsData = [
  {
    title: "1-комн. квартира, 33,4 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "2-комн. квартира, 50,9 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_817_500,
    status: "сдана",
  },
  {
    title: "Коттедж «На Высоте»",
    developer: "в ЖК «Парк Победы», Литер 5",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. Героя Пешкова, 14лит4",
    type: "Новостройки",
    price: 8_068_800,
    status: "сдана",
  },
  {
    title: "2-комн. квартира, 63,36 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location:
      "Краснодар городской округ, Знаменский поселок, Родные Просторы микрорайон",
    type: "Новостройки",
    price: 4_847_200,
    status: "сдана",
  },
  {
    title: "1-комн. квартира, 33,5 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "2-комн. квартира, 49,81 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "1-комн. квартира, 35,67 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "2-комн. квартира, 45,09 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "2-комн. квартира, 65 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "2-комн. квартира, 51,4 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "1-комн. квартира, 30 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "2-комн. квартира, 54 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Новостройки",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "Коттедж, 59 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Коттеджи",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "Вторичное жилье, 57 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Вторичка",
    price: 3_273_200,
    status: "сдана",
  },
  {
    title: "Дом, 58 м²",
    developer: "в ЖК «Зеленодар», Дом 1/3",
    image: "/images/buildings/image1.png",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    type: "Дома",
    price: 3_273_200,
    status: "сдана",
  },
];

export default buildingsData;
