const cottages = [
  {
    id: 1,
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 4,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 2,
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 2.8,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 3,
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 3,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 4,
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 2.8,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 5,
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 1,
    image: "/largeHouses/img3.jpg",
  },
];
export default cottages;
