const developersCardRating = [
  {
    id: "1",
    image: "/images/developers/CCK.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "2",

    image: "/images/developers/Dogma.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "3",

    image: "/images/developers/wkb.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "4",

    image: "/images/developers/yugimper.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
  {
    id: "5",
    image: "/images/developers/yuginvest.svg",
    place: 1,
    quantityComplexes: 16,
    quantityCottages: 10,
  },
];

export default developersCardRating;
