const homeData = [
  {
    id: 1,
    type: "Коттеджи",
    title: "коттедж, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 4,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 2,
    type: "Коттеджи",

    title: "коттедж, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 2.8,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 3,
    type: "Коттеджи",

    title: "коттедж, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 3,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 4,
    type: "Коттеджи",

    title: "коттедж, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 2.8,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 5,
    type: "Коттеджи",

    title: "коттедж, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    rating: 1,
    image: "/largeHouses/img3.jpg",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 2.8,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "лучше вторичное жилье",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Вторичка",
    status: "сдана",
    rating: 3.5,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "Лучший дом в мире",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Дома",
    status: "сдана",
    rating: 1,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "Лучший коттедж в мире",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Коттеджи",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.9,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.8,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
  {
    id: 5,

    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    type: "Новостройки",
    status: "сдана",
    rating: 4.7,
    image: "/cards/home.png",
  },
];
export default homeData;
