const homeWithoutRatingData = [
  {
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    image: "/cards/home.png",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    image: "/cards/home.png",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    image: "/cards/home.png",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    image: "/cards/home.png",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    image: "/cards/home.png",
  },
  {
    title: "1-комн. квартира, 33,4 м²",
    description: "в ЖК «Зеленодар», Дом 1/3",
    location: "Краснодар, Прикубанский, ул. 3-я Трудовая, 1/3",
    price: 120_000_000,
    status: "сдана",
    image: "/cards/home.png",
  },
];
export default homeWithoutRatingData;
