const largeHouses = [
  {
    title: "Изумрудный город",
    description: "4-этажный коттедж, 915 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 483_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img1.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img2.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус2»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img3.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус3»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img4.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус3»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img5.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хау5»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img6.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус6»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img7.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Коттеджный посёлок «Лайт Хаус7»",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Коттедж",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img8.jpg",
  },
  {
    title: "Я участок",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Участок",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img9.jpg",
  },
  {
    title: "Я таунхаух",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Таунхауз",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img10.jpg",
  },
  {
    title: "Я дом",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Дом",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img10.jpg",
  },
  {
    title: "Я дом",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Дом",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img10.jpg",
  },
  {
    title: "Я дом",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Дом",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img10.jpg",
  },
  {
    title: "Я дом",
    description: "от 363 м² до 563 м²",
    location: "г. Краснодар, Российский посёлок, Краснодар",
    price: 43_000_000,
    type: "Дом",
    status: "833 333 ₽/сот",
    image: "/largeHouses/img10.jpg",
  },
];

export default largeHouses;
