const addFilterData = [
  {
    name: "Общая площадь",
    key: "overallSquare",
    type: "range",
  },
  {
    name: "Площадь кухни",
    key: "kitchenSquare",
    type: "range",
  },
  {
    name: "Расстояние до метро",
    key: "subwayDistance",
    type: "radio",
    variants: ["Пешком", "Транспорт", "Любое"],
  },
  {
    name: "Ремонт",
    key: "repair",
    type: "checkbox",
    variants: ["Без ремонта", "Дизайнерский", "Евроремонт", "Косметический"],
  },
  {
    name: "Этаж",
    key: "floor",
    variants: ["Не последний", "Не первый", "Последний"],
    type: "mished",
  },
  {
    name: "Балкон / Лоджия",
    key: "balcony",
    type: "checkbox",
    variants: ["1", "2", "3+"],
  },
  {
    name: "Сан узел",
    key: "toilet",
    type: "checkbox",
    variants: ["Совмещенный", "Раздельный"],
  },
  {
    name: "Высота потолка",
    key: "height",
    type: "checkbox",
    variants: ["от 2,5 м", "от 2,7 м", "от 3 м", "от 4 м"],
  },
  {
    name: "Лифт",
    key: "elevator",
    type: "checkbox",
    variants: ["Грузовой", "Пассажирский"],
  },
  {
    name: "Тип продажи",
    key: "buyType",
    type: "checkbox",
    variants: ["В ипотеку", "Свободная", "Альтернатива"],
  },
  {
    name: "Материалы стен",
    key: "wall",
    type: "checkbox",
    variants: [
      "Монолит",
      "Панельный",
      "Газобетонный",
      "Деревянный",
      "Щитовой",
      "Кирпичный",
      "Блочный",
      "Пенобетонный",
      "Красный",
      "Металл",
    ],
  },
  {
    name: "Год сдачи ЖК",
    key: "yearComplex",
    type: "range",
  },
  {
    name: "Год постройки дома",
    key: "yearHouse",
    type: "range",
  },
  {
    name: "Этажность дома",
    key: "houseFloor",
    type: "range",
  },
  {
    name: "Застройщик",
    key: "developer",
    type: "checkbox-accord",
    variants: [
      "ССК",
      "ВКБ-новостройки",
      "Dogma",
      "ЮгСтройИнвест",
      "ЮгСтройИмпериал",
    ],
  },
  {
    name: "Застройщик",
    key: "developer",
    type: "select",
    options: ["MaximStroi", "IvanStroi", "YaEblanStroi"],
  },
  {
    name: "Площадь участка",
    key: "lotSquare",
    type: "range",
  },
  {
    name: "Статус участка",
    key: "lotStatus",
    type: "checkbox",
    variants: ["ИЖС", "Фермерский", "Садовый"],
  },
  {
    name: "Инфраструктура и коммуникации",
    key: "infrastructure",
    type: "checkbox",
    variants: [
      "Газ",
      "Канализация",
      "Водоснабжение",
      "Отопление",
      "Электричество",
    ],
  },
  {
    name: "Дата публикации",
    key: "publDate",
    type: "checkbox",
    variants: ["Сегодня", "За сутки", "За 30 дней", "За все время"],
  },
];
export default addFilterData;
